/** Comprehensive chart story registry for the Graphein gallery. */
import type { ChartSpec, GeoFeatureCollection } from 'graphein';
import {
  boxDistributions,
  categorical,
  choroplethMetric,
  heatmapGrid,
  rng,
  salesTable,
  sankeyFlows,
  scatter,
  timeSeries,
} from '../content/data';
import usStatesRaw from '../content/us-states.albers.json';
import type { Story, StoryArgs, StoryControl } from './types';

const usStates = usStatesRaw as unknown as GeoFeatureCollection;
const usStateNames = usStates.features.map((f) => (f.properties?.name as string | undefined) ?? '').filter(Boolean);
const REGIONS = ['West', 'East', 'North', 'South'];
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const money = '$,.0f';

const ctl = {
  toggle: (id: string, label: string, def = false): StoryControl => ({ id, kind: 'toggle', label, default: def }),
  range: (id: string, label: string, min: number, max: number, step: number, def: number): StoryControl => ({
    id,
    kind: 'range',
    label,
    min,
    max,
    step,
    default: def,
  }),
};
const round = (v: number, dp = 2) => Math.round(v * 10 ** dp) / 10 ** dp;
const story = (s: Story) => s;

function commerce() {
  return MONTHS.map((month, i) => ({
    month,
    bookings: Math.round(420 + i * 34 + Math.sin(i / 1.7) * 60),
    pipeline: Math.round(880 + i * 45 + Math.cos(i / 2) * 95),
    conversion: round(0.038 + i * 0.0028 + Math.sin(i / 2.3) * 0.006, 4),
    satisfaction: round(78 + i * 0.7 + Math.sin(i / 1.8) * 4, 1),
  }));
}
function normalizedLeads() {
  const rows = timeSeries({ series: ['Organic', 'Paid search', 'Partners', 'Product-led'], points: 18, seed: 17, base: 80 });
  const totals = new Map<number, number>();
  rows.forEach((d) => totals.set((d.date as Date).getTime(), (totals.get((d.date as Date).getTime()) ?? 0) + Number(d.value)));
  return rows.map((d) => ({ ...d, share: round(Number(d.value) / (totals.get((d.date as Date).getTime()) ?? 1), 4) }));
}
function latency(n = 320) {
  const r = rng(24);
  return Array.from({ length: n }, (_, i) => ({
    latency_ms: round(18 - Math.log(1 - r()) * 42 + (r() > 0.9 ? -Math.log(1 - r()) * 95 : 0) + (i % 7) * 1.8, 1),
  }));
}
function signalData(points = 50000) {
  const r = rng(12);
  let level = 100;
  return Array.from({ length: points }, (_, sample) => {
    level += 0.03 + (r() - 0.48) * 1.2;
    return { sample, value: round(Math.max(0, level + Math.sin(sample / 90) * 18 + (r() - 0.5) * 9), 2) };
  });
}
function calendar(year = 2024) {
  const r = rng(64);
  const start = new Date(Date.UTC(year, 0, 1));
  return Array.from({ length: 366 }, (_, i) => {
    const date = new Date(start.getTime() + i * 86_400_000);
    const dow = date.getUTCDay();
    const launch = i > 238 && i < 282 ? 10 : 0;
    return {
      date: date.toISOString().slice(0, 10),
      commits: Math.max(0, Math.round(7 + Math.sin((i / 366) * Math.PI * 2 - 0.8) * 5 + (dow === 0 || dow === 6 ? -5 : 4) + launch + r() * 8)),
    };
  });
}
function tableRows() {
  return salesTable({ n: 18, seed: 91 }).map((d, i) => ({
    ...d,
    account: ['Northwind', 'Contoso', 'Fabrikam', 'Adventure Works', 'Tailspin', 'Litware'][i % 6],
    risk: Number(d.margin) < 0.18 ? 'High' : Number(d.margin) < 0.32 ? 'Medium' : 'Low',
    riskScore: Number(d.margin) < 0.18 ? 3 : Number(d.margin) < 0.32 ? 2 : 1,
  }));
}
const browserShare = [
  { browser: 'Chrome', share: 53.02 },
  { browser: 'Safari', share: 18.61 },
  { browser: 'Edge', share: 11.4 },
  { browser: 'Firefox', share: 7.07 },
  { browser: 'Samsung Internet', share: 4.12 },
  { browser: 'Opera', share: 2.43 },
  { browser: 'Other', share: 3.35 },
];

export const chartStories: Story[] = [
  story({
    id: 'line-single',
    group: 'Line',
    title: 'Line — weekly active users',
    blurb: 'A clean product-health trend with optional area fill, smoothing, and automatic high/low callouts.',
    tags: ['temporal', 'trend', 'insights'],
    controls: [ctl.range('points', 'Points', 8, 120, 4, 52), ctl.toggle('area', 'Fill area'), ctl.toggle('curve', 'Smooth curve'), ctl.toggle('insights', 'Auto insights', true)],
    spec: (a: StoryArgs = {}) => ({
      type: 'line',
      data: timeSeries({ points: Number(a.points ?? 52), seed: 3, base: 4200, trend: 42, seasonAmp: 380, noise: 110 }),
      encoding: { x: { field: 'date', type: 'temporal' }, y: { field: 'value', title: 'Active users', format: ',.0f' } },
      area: Boolean(a.area),
      curve: a.curve ? 'monotone' : undefined,
      insights: Boolean(a.insights),
      title: { text: 'Weekly active users', subtitle: 'Auto callouts mark the highest and lowest weeks' },
    }),
  }),
  story({
    id: 'line-regional-revenue',
    group: 'Line',
    title: 'Line — regional revenue race',
    blurb: 'Multiple tidy series share one temporal x-axis; optional regression labels show trend strength by region.',
    tags: ['series', 'legend', 'trendline'],
    controls: [ctl.toggle('trendline', 'Trendline + R²', true)],
    spec: (a: StoryArgs = {}) => ({
      type: 'line',
      data: timeSeries({ series: REGIONS, points: 48, seed: 5, base: 180, trend: 2.8, seasonAmp: 24, noise: 12 }),
      encoding: { x: { field: 'date', type: 'temporal' }, y: { field: 'value', title: 'Revenue ($k)', format: money }, series: { field: 'series' } },
      trendline: a.trendline ? { label: true } : undefined,
      title: { text: 'Revenue by region', subtitle: 'One regression per region when split by series' },
    }),
  }),
  story({
    id: 'line-channel-facets',
    group: 'Line',
    title: 'Line — acquisition small multiples',
    blurb: 'Faceting creates comparable channel panels from one field without hand-building separate charts.',
    tags: ['facet', 'small-multiples'],
    wide: true,
    spec: () => ({
      type: 'line',
      data: timeSeries({ series: ['Organic', 'Paid search', 'Partners', 'Lifecycle'], points: 30, seed: 16, base: 950, trend: 9, seasonAmp: 95, noise: 42 }),
      encoding: { x: { field: 'date', type: 'temporal' }, y: { field: 'value', title: 'Qualified leads', format: ',.0f' }, series: { field: 'series' } },
      facet: { field: 'series', columns: 2 },
      points: true,
      title: 'Qualified leads by acquisition channel',
    }),
  }),
  story({
    id: 'line-dense-lttb',
    group: 'Line',
    title: 'Line — 50k point signal',
    blurb: 'A dense telemetry trace remains crisp because Graphein downsamples the draw path while preserving extrema.',
    tags: ['big-data', 'lttb'],
    wide: true,
    spec: () => ({
      type: 'line',
      data: signalData(),
      encoding: { x: { field: 'sample', title: 'Sample' }, y: { field: 'value', title: 'Signal' } },
      title: { text: 'High-frequency service signal', subtitle: '50,000 points, downsampled for fast rendering' },
    }),
  }),

  story({
    id: 'area-stacked-demand',
    group: 'Area',
    title: 'Area — stacked demand mix',
    blurb: 'Stacked areas show both total load and each region’s contribution over time.',
    tags: ['stack', 'composition'],
    controls: [ctl.toggle('curve', 'Smooth curve', true)],
    spec: (a: StoryArgs = {}) => ({
      type: 'area',
      data: timeSeries({ series: REGIONS, points: 36, seed: 6, base: 120, trend: 1.7, seasonAmp: 20, noise: 9 }),
      encoding: { x: { field: 'date', type: 'temporal' }, y: { field: 'value', title: 'Load (MW)' }, series: { field: 'series' } },
      stack: true,
      curve: a.curve ? 'monotone' : 'linear',
      title: 'Regional demand stack',
    }),
  }),
  story({
    id: 'area-normalized-channel-share',
    group: 'Area',
    title: 'Area — normalized channel share',
    blurb: 'Pre-normalized shares turn a stacked area into a 100% mix-shift view.',
    tags: ['normalized', 'share'],
    spec: () => ({
      type: 'area',
      data: normalizedLeads(),
      encoding: { x: { field: 'date', type: 'temporal' }, y: { field: 'share', title: 'Share of leads', format: '.0%' }, series: { field: 'series' } },
      stack: true,
      title: { text: 'Lead mix by channel', subtitle: 'Each date sums to 100%' },
    }),
  }),

  story({
    id: 'bar-quarter-region',
    group: 'Bar',
    title: 'Bar — grouped or stacked revenue',
    blurb: 'Toggle side-by-side comparison and stacked totals without reshaping the tidy categorical rows.',
    tags: ['category', 'grouped', 'stacked'],
    wide: true,
    controls: [ctl.toggle('stack', 'Stack')],
    spec: (a: StoryArgs = {}) => ({
      type: 'bar',
      data: categorical({ categories: ['Q1', 'Q2', 'Q3', 'Q4'], series: REGIONS, seed: 12, base: 260, noise: 75 }),
      encoding: { x: { field: 'category' }, y: { field: 'value', title: 'Revenue ($k)', format: money }, series: { field: 'series' } },
      stack: Boolean(a.stack),
      cornerRadius: 5,
      title: 'Revenue by quarter and region',
    }),
  }),
  story({
    id: 'bar-horizontal-priorities',
    group: 'Bar',
    title: 'Bar — horizontal roadmap priorities',
    blurb: 'Horizontal bars keep long labels readable while preserving instant rank comparison.',
    tags: ['rank', 'horizontal'],
    spec: () => ({
      type: 'bar',
      data: [
        { priority: 'Onboarding', score: 91 },
        { priority: 'Procurement', score: 77 },
        { priority: 'Templates', score: 72 },
        { priority: 'Checkout', score: 66 },
        { priority: 'Renewals', score: 58 },
      ],
      encoding: { x: { field: 'priority' }, y: { field: 'score', title: 'Opportunity score' } },
      orientation: 'horizontal',
      cornerRadius: 7,
      insights: true,
      title: 'Roadmap opportunity score',
    }),
  }),
  story({
    id: 'bar-faceted-segments',
    group: 'Bar',
    title: 'Bar — segment small multiples',
    blurb: 'A faceted bar grid compares plan mix across customer segments without pre-splitting data.',
    tags: ['facet', 'segments'],
    wide: true,
    spec: () => ({
      type: 'bar',
      data: [
        ...categorical({ categories: ['Starter', 'Team', 'Business', 'Enterprise'], series: ['Consumer'], seed: 31, categoryField: 'plan' }),
        ...categorical({ categories: ['Starter', 'Team', 'Business', 'Enterprise'], series: ['Corporate'], seed: 32, base: 160, categoryField: 'plan' }),
        ...categorical({ categories: ['Starter', 'Team', 'Business', 'Enterprise'], series: ['Public sector'], seed: 33, base: 110, categoryField: 'plan' }),
      ],
      encoding: { x: { field: 'plan' }, y: { field: 'value', title: 'Accounts' }, series: { field: 'series' } },
      facet: { field: 'series', columns: 3 },
      cornerRadius: 4,
      title: 'Plan mix by customer segment',
    }),
  }),

  story({
    id: 'scatter-bubbles',
    group: 'Scatter',
    title: 'Scatter — grouped bubbles',
    blurb: 'Bubble size and color add portfolio context to a spend-versus-return plot.',
    tags: ['correlation', 'bubble'],
    controls: [ctl.toggle('trendline', 'Trendline + R²', true)],
    spec: (a: StoryArgs = {}) => ({
      type: 'scatter',
      data: scatter({ n: 90, groups: ['Alpha', 'Beta', 'Gamma'], seed: 11 }),
      encoding: { x: { field: 'x', title: 'Spend index' }, y: { field: 'y', title: 'Return index' }, color: { field: 'group' }, size: { field: 'size', title: 'Deal size' } },
      trendline: a.trendline ? { label: true } : undefined,
      title: 'Spend versus return by portfolio',
    }),
  }),
  story({
    id: 'scatter-faceted-experiments',
    group: 'Scatter',
    title: 'Scatter — experiment cohorts',
    blurb: 'Facets reveal whether each cohort shares the same efficiency frontier.',
    tags: ['facet', 'experiments'],
    wide: true,
    spec: () => ({
      type: 'scatter',
      data: scatter({ n: 55, groups: ['Control', 'Variant A', 'Variant B', 'Variant C'], seed: 19 }),
      encoding: { x: { field: 'x', title: 'Exposure' }, y: { field: 'y', title: 'Activation' }, color: { field: 'group' }, size: { field: 'size' } },
      facet: { field: 'group', columns: 2 },
      trendline: { label: true },
      title: 'Activation efficiency by experiment cohort',
    }),
  }),

  story({
    id: 'combo-revenue-conversion',
    group: 'Combo',
    title: 'Combo — revenue and conversion',
    blurb: 'A bar-and-line combo pairs scale and rate metrics on separate axes.',
    tags: ['dual-axis', 'bar-line'],
    wide: true,
    spec: () => ({
      type: 'combo',
      data: commerce(),
      encoding: { x: { field: 'month', title: 'Month' } },
      layers: [
        { mark: 'bar', name: 'Bookings', cornerRadius: 5, encoding: { y: { field: 'bookings', title: 'Bookings ($k)', format: money } } },
        { mark: 'line', name: 'Conversion', axis: 'right', points: true, encoding: { y: { field: 'conversion', title: 'Conversion rate', format: '.1%' } } },
      ],
      title: { text: 'Bookings versus conversion rate', subtitle: 'Shared months, independent y-axes' },
    }),
  }),
  story({
    id: 'combo-pipeline-satisfaction',
    group: 'Combo',
    title: 'Combo — pipeline and satisfaction',
    blurb: 'Area, bar, and line layers form a compact monthly operating view from one flat array.',
    tags: ['layers', 'ops'],
    wide: true,
    spec: () => ({
      type: 'combo',
      data: commerce(),
      encoding: { x: { field: 'month' } },
      layers: [
        { mark: 'area', name: 'Pipeline', encoding: { y: { field: 'pipeline', title: 'Pipeline ($k)', format: money } } },
        { mark: 'bar', name: 'Bookings', cornerRadius: 4, encoding: { y: { field: 'bookings', title: 'Bookings ($k)', format: money } } },
        { mark: 'line', name: 'Satisfaction', axis: 'right', points: true, encoding: { y: { field: 'satisfaction', title: 'CSAT', format: ',.0f' } } },
      ],
      title: 'Pipeline, bookings, and customer satisfaction',
    }),
  }),

  story({
    id: 'histogram-latency',
    group: 'Histogram',
    title: 'Histogram — request latency',
    blurb: 'Raw observations are binned inside the spec so the distribution stays inspectable.',
    tags: ['distribution', 'bins'],
    controls: [ctl.range('bins', 'Max bins', 8, 40, 2, 22), ctl.toggle('density', 'Density')],
    spec: (a: StoryArgs = {}) => ({
      type: 'histogram',
      data: latency(),
      encoding: { x: { field: 'latency_ms', title: 'Latency (ms)' } },
      bin: { maxbins: Number(a.bins ?? 22) },
      density: Boolean(a.density),
      cornerRadius: 2,
      title: 'API request latency distribution',
    }),
  }),
  story({
    id: 'histogram-order-value',
    group: 'Histogram',
    title: 'Histogram — order value density',
    blurb: 'A density histogram highlights shape rather than absolute count.',
    tags: ['density', 'orders'],
    spec: () => ({
      type: 'histogram',
      data: salesTable({ n: 320, seed: 44 }),
      encoding: { x: { field: 'sales', title: 'Order value', format: money } },
      bin: { maxbins: 18 },
      density: true,
      cornerRadius: 2,
      title: 'Order value density',
    }),
  }),

  story({
    id: 'box-latency-cohorts',
    group: 'Box',
    title: 'Box — latency by plan',
    blurb: 'Quartiles, whiskers, and outliers expose both typical response and long-tail incidents.',
    tags: ['distribution', 'outliers'],
    spec: () => ({
      type: 'box',
      data: boxDistributions({ categories: ['Free', 'Team', 'Business', 'Enterprise', 'Strategic'], n: 90, seed: 41, base: 64, spread: 13 }),
      encoding: { x: { field: 'category' }, y: { field: 'value', title: 'Latency (ms)' } },
      title: { text: 'Response time by plan', subtitle: 'Tukey whiskers · 1.5×IQR' },
    }),
  }),
  story({
    id: 'box-release-comparison',
    group: 'Box',
    title: 'Box — before/after release spread',
    blurb: 'Grouped boxes compare raw distributions for two releases across the same tiers.',
    tags: ['grouped', 'release'],
    wide: true,
    spec: () => ({
      type: 'box',
      data: boxDistributions({ categories: ['Self-serve', 'SMB', 'Mid-market', 'Enterprise'], series: ['Before', 'After'], n: 70, seed: 52, base: 72, spread: 11 }),
      encoding: { x: { field: 'category' }, y: { field: 'value', title: 'Task completion time (sec)' }, series: { field: 'series' } },
      title: 'Workflow speed before and after release',
    }),
  }),

  story({
    id: 'pie-browser-share',
    group: 'Pie',
    title: 'Pie — browser share',
    blurb: 'Automatic callout labels keep thin slices readable while preserving a familiar share-of-total view.',
    tags: ['share', 'callouts'],
    controls: [ctl.toggle('donut', 'Donut', true)],
    spec: (a: StoryArgs = {}) => ({
      type: 'pie',
      data: browserShare,
      encoding: { theta: { field: 'share', title: 'Share', format: '.1f' }, color: { field: 'browser' } },
      donut: a.donut ? 0.55 : false,
      labels: { placement: 'auto', content: 'category-percent', connector: 'slice', minShare: 0.01 },
      legend: false,
      title: 'Browser share across customer sessions',
    }),
  }),
  story({
    id: 'pie-budget-donut',
    group: 'Pie',
    title: 'Pie — operating budget donut',
    blurb: 'Donut rings work best for a small number of meaningful slices with strong labels.',
    tags: ['budget', 'donut'],
    spec: () => ({
      type: 'pie',
      data: [
        { area: 'Engineering', spend: 38 },
        { area: 'Customer success', spend: 18 },
        { area: 'Sales', spend: 21 },
        { area: 'Marketing', spend: 14 },
        { area: 'Operations', spend: 9 },
      ],
      encoding: { theta: { field: 'spend', title: 'Budget share', format: '.0f' }, color: { field: 'area' } },
      donut: 0.62,
      labels: { placement: 'outside', content: 'category-percent', connector: 'muted' },
      title: 'Operating budget allocation',
    }),
  }),

  story({
    id: 'treemap-product-revenue',
    group: 'Treemap',
    title: 'Treemap — product revenue',
    blurb: 'Nested rectangles fit a full product portfolio into one compact stage while preserving parent groups.',
    tags: ['hierarchy', 'portfolio'],
    wide: true,
    spec: () => ({
      type: 'treemap',
      data: [
        { group: 'Core platform', category: 'Workflow automation', revenue: 420, growth: 18 },
        { group: 'Core platform', category: 'Data sync', revenue: 310, growth: 11 },
        { group: 'Core platform', category: 'Governance', revenue: 180, growth: 8 },
        { group: 'AI suite', category: 'Assistant seats', revenue: 360, growth: 34 },
        { group: 'AI suite', category: 'Evaluation tools', revenue: 170, growth: 28 },
        { group: 'Experience', category: 'Dashboards', revenue: 260, growth: 15 },
        { group: 'Experience', category: 'Templates', revenue: 130, growth: 21 },
        { group: 'Services', category: 'Enablement', revenue: 90, growth: 6 },
      ],
      encoding: {
        group: { field: 'group' },
        category: { field: 'category' },
        value: { field: 'revenue', title: 'Revenue ($k)', format: money },
        color: { field: 'growth', title: 'Growth %' },
      },
      scheme: 'teal',
      title: 'Revenue by product area',
    }),
  }),
  story({
    id: 'treemap-cloud-costs',
    group: 'Treemap',
    title: 'Treemap — cloud cost composition',
    blurb: 'A grouped treemap separates infrastructure cost centers from the services driving them.',
    tags: ['cost', 'cloud'],
    wide: true,
    spec: () => ({
      type: 'treemap',
      data: [
        { group: 'Compute', category: 'API workers', cost: 148 },
        { group: 'Compute', category: 'Batch jobs', cost: 92 },
        { group: 'Compute', category: 'ML inference', cost: 121 },
        { group: 'Storage', category: 'Warehouse', cost: 104 },
        { group: 'Storage', category: 'Object store', cost: 64 },
        { group: 'Network', category: 'CDN', cost: 58 },
        { group: 'Network', category: 'Egress', cost: 73 },
        { group: 'Observability', category: 'Logs', cost: 46 },
      ],
      encoding: { group: { field: 'group' }, category: { field: 'category' }, value: { field: 'cost', title: 'Monthly cost ($k)', format: money } },
      labels: true,
      title: 'Monthly cloud cost by service',
    }),
  }),

  story({
    id: 'funnel-signup',
    group: 'Funnel',
    title: 'Funnel — signup activation',
    blurb: 'Funnel stages show where prospects convert, stall, and return for renewal.',
    tags: ['conversion', 'activation'],
    controls: [
      {
        id: 'percent',
        kind: 'select',
        label: 'Percent basis',
        options: [
          { value: 'first', label: 'First stage' },
          { value: 'previous', label: 'Previous stage' },
        ],
        default: 'first',
      },
    ],
    spec: (a: StoryArgs = {}) => ({
      type: 'funnel',
      data: [
        { stage: 'Visited pricing', users: 12480 },
        { stage: 'Started trial', users: 5210 },
        { stage: 'Connected data', users: 3120 },
        { stage: 'Invited teammate', users: 1840 },
        { stage: 'Subscribed', users: 1430 },
        { stage: 'Renewed', users: 820 },
      ],
      encoding: { stage: { field: 'stage' }, value: { field: 'users', title: 'Users', format: ',.0f' } },
      percent: a.percent === 'previous' ? 'previous' : 'first',
      title: { text: 'Signup funnel', subtitle: 'Where prospects become retained customers' },
    }),
  }),

  story({
    id: 'heatmap-traffic-week-hour',
    group: 'Heatmap',
    title: 'Heatmap — traffic by week and hour',
    blurb: 'Two-category density makes lunch peaks, weekend dips, and overnight quiet hours obvious.',
    tags: ['grid', 'density'],
    wide: true,
    spec: () => ({
      type: 'heatmap',
      data: heatmapGrid(),
      encoding: { x: { field: 'hour' }, y: { field: 'day' }, color: { field: 'value', type: 'quantitative', title: 'Requests' } },
      scheme: 'teal',
      title: 'Traffic by day and hour',
    }),
  }),
  story({
    id: 'heatmap-support-sla',
    group: 'Heatmap',
    title: 'Heatmap — support SLA pressure',
    blurb: 'Queue and severity pressure can be scanned without collapsing one operational dimension away.',
    tags: ['support', 'sla'],
    spec: () => ({
      type: 'heatmap',
      data: heatmapGrid({ rows: ['P0 incident', 'P1 urgent', 'P2 normal', 'P3 question'], cols: ['Billing', 'Auth', 'Integrations', 'Data', 'Mobile', 'Admin'], seed: 77 }),
      encoding: { x: { field: 'hour', title: 'Queue' }, y: { field: 'day', title: 'Severity' }, color: { field: 'value', type: 'quantitative', title: 'Open tickets' } },
      scheme: 'teal',
      title: 'Open support tickets by queue and severity',
    }),
  }),

  story({
    id: 'calendar-activity-year',
    group: 'Calendar heatmap',
    title: 'Calendar heatmap — daily activity',
    blurb: 'A full-year calendar reveals weekday habits, seasonal launch spikes, and quiet holiday bands.',
    tags: ['calendar', 'daily'],
    wide: true,
    spec: () => ({
      type: 'calendarHeatmap',
      data: calendar(2024),
      encoding: { date: { field: 'date', type: 'temporal' }, color: { field: 'commits', type: 'quantitative', title: 'Commits' } },
      scheme: 'teal',
      title: { text: 'Daily engineering activity', subtitle: '2024 contribution-style activity map' },
    }),
  }),

  story({
    id: 'kpi-arr',
    group: 'KPI',
    title: 'KPI — ARR with sparkline',
    blurb: 'A headline metric, directional delta, and tiny trendline make a compact scorecard tile.',
    tags: ['metric', 'sparkline'],
    height: 240,
    spec: () => ({
      type: 'kpi',
      data: timeSeries({ points: 14, stepDays: 30, base: 5200, trend: 70, seasonAmp: 520, noise: 180, seed: 5, valueField: 'sales' }),
      value: { field: 'sales', aggregate: 'sum' },
      label: 'Annual recurring revenue',
      delta: 0.124,
      format: money,
      sparkline: { field: 'sales' },
      title: 'ARR momentum',
    }),
  }),
  story({
    id: 'kpi-nps-health',
    group: 'KPI',
    title: 'KPI — NPS health',
    blurb: 'Literal KPI values work when the number already comes from an upstream model.',
    tags: ['nps', 'health'],
    height: 220,
    spec: () => ({ type: 'kpi', value: 61, label: 'Net promoter score', delta: 0.08, format: ',.0f', title: 'Customer advocacy pulse' }),
  }),

  story({
    id: 'gauge-service-health',
    group: 'Gauge',
    title: 'Gauge — service health',
    blurb: 'A radial gauge emphasizes one operational value against a target and qualitative bands.',
    tags: ['target', 'bands'],
    height: 300,
    spec: () => ({
      type: 'gauge',
      data: [{ uptime: 99.2 }, { uptime: 98.7 }, { uptime: 99.6 }],
      value: { field: 'uptime', aggregate: 'mean' },
      min: 90,
      max: 100,
      target: 99,
      label: 'Average uptime',
      format: ',.1f',
      bands: [{ to: 96 }, { to: 99 }, { to: 100 }],
      title: 'Service availability',
    }),
  }),
  story({
    id: 'gauge-capacity',
    group: 'Gauge',
    title: 'Gauge — warehouse capacity',
    blurb: 'Gauges are effective for bounded resource levels with a meaningful maximum and target.',
    tags: ['capacity', 'target'],
    height: 300,
    spec: () => ({
      type: 'gauge',
      value: 76,
      min: 0,
      max: 100,
      target: 82,
      label: 'Capacity used',
      format: ',.0f',
      bands: [{ to: 60 }, { to: 85 }, { to: 100 }],
      title: 'Warehouse capacity utilization',
    }),
  }),

  story({
    id: 'bullet-quarterly-revenue',
    group: 'Bullet',
    title: 'Bullet — quarterly revenue',
    blurb: 'Bullet graphs fit goal tracking into a tight horizontal space with ranges and a target marker.',
    tags: ['target', 'compact'],
    height: 220,
    spec: () => ({
      type: 'bullet',
      title: 'Quarterly revenue attainment',
      label: 'Revenue',
      value: 820000,
      target: 900000,
      min: 0,
      max: 1000000,
      ranges: [600000, 800000, 1000000],
      format: money,
    }),
  }),
  story({
    id: 'bullet-support-sla',
    group: 'Bullet',
    title: 'Bullet — support SLA',
    blurb: 'A compact SLA indicator shows whether the team is inside the target band.',
    tags: ['sla', 'support'],
    height: 220,
    spec: () => ({ type: 'bullet', title: 'Priority support response time', label: 'Median response', value: 42, target: 30, min: 0, max: 90, ranges: [30, 45, 60], format: ',.0f' }),
  }),

  story({
    id: 'waterfall-cash-bridge',
    group: 'Waterfall',
    title: 'Waterfall — cash bridge',
    blurb: 'Signed deltas show how inflows and outflows build from opening to closing cash.',
    tags: ['bridge', 'finance'],
    wide: true,
    spec: () => ({
      type: 'waterfall',
      data: [
        { stage: 'Opening', delta: 1200 },
        { stage: 'Product revenue', delta: 540 },
        { stage: 'Services revenue', delta: 320 },
        { stage: 'Churn', delta: -180 },
        { stage: 'Refunds', delta: -90 },
        { stage: 'Opex', delta: -260 },
        { stage: 'Closing', delta: 0 },
      ],
      totals: ['Opening', 'Closing'],
      encoding: { stage: { field: 'stage' }, value: { field: 'delta', title: 'USD (000s)', format: money } },
      cornerRadius: 4,
      title: 'FY cash flow bridge',
    }),
  }),
  story({
    id: 'waterfall-margin-walk',
    group: 'Waterfall',
    title: 'Waterfall — margin walk',
    blurb: 'A margin walk separates pricing, mix, savings, and cost pressure before the net change.',
    tags: ['margin', 'operations'],
    wide: true,
    spec: () => ({
      type: 'waterfall',
      data: [
        { stage: 'Starting margin', delta: 34 },
        { stage: 'Pricing', delta: 6 },
        { stage: 'Cloud savings', delta: 4 },
        { stage: 'Enterprise mix', delta: 3 },
        { stage: 'Support load', delta: -5 },
        { stage: 'FX', delta: -2 },
      ],
      showTotal: true,
      totalLabel: 'Ending margin',
      encoding: { stage: { field: 'stage' }, value: { field: 'delta', title: 'Margin points', format: ',.0f' } },
      title: 'Gross margin movement',
    }),
  }),

  story({
    id: 'slope-market-share',
    group: 'Slope',
    title: 'Slope — market share shift',
    blurb: 'Slope charts strip before/after comparison down to who rose, who fell, and by how much.',
    tags: ['before-after', 'rank'],
    spec: () => ({
      type: 'slope',
      data: [
        { year: '2019', brand: 'Aurora', share: 34 },
        { year: '2024', brand: 'Aurora', share: 22 },
        { year: '2019', brand: 'Borealis', share: 18 },
        { year: '2024', brand: 'Borealis', share: 29 },
        { year: '2019', brand: 'Cirrus', share: 27 },
        { year: '2024', brand: 'Cirrus', share: 31 },
        { year: '2019', brand: 'Delta', share: 21 },
        { year: '2024', brand: 'Delta', share: 18 },
      ],
      encoding: { x: { field: 'year' }, y: { field: 'share', title: 'Share %' }, series: { field: 'brand' } },
      colorByChange: true,
      format: ',.0f',
      title: 'Market share shift, 2019 → 2024',
    }),
  }),
  story({
    id: 'slope-renewal-rate',
    group: 'Slope',
    title: 'Slope — renewal rate movement',
    blurb: 'Direct end labels keep segment-by-segment movement legible without a legend.',
    tags: ['renewal', 'segments'],
    spec: () => ({
      type: 'slope',
      data: [
        { period: 'Before', segment: 'Startup', renewal: 72 },
        { period: 'After', segment: 'Startup', renewal: 81 },
        { period: 'Before', segment: 'SMB', renewal: 78 },
        { period: 'After', segment: 'SMB', renewal: 84 },
        { period: 'Before', segment: 'Mid-market', renewal: 86 },
        { period: 'After', segment: 'Mid-market', renewal: 88 },
        { period: 'Before', segment: 'Enterprise', renewal: 91 },
        { period: 'After', segment: 'Enterprise', renewal: 89 },
      ],
      encoding: { x: { field: 'period' }, y: { field: 'renewal', title: 'Renewal rate' }, series: { field: 'segment' } },
      colorByChange: true,
      format: ',.0f',
      title: 'Renewal rate before and after success playbook',
    }),
  }),

  story({
    id: 'dumbbell-life-expectancy',
    group: 'Dumbbell',
    title: 'Dumbbell — life expectancy gains',
    blurb: 'Connected dots encode the gap between two groups per category and sort by movement.',
    tags: ['gap', 'before-after'],
    spec: () => ({
      type: 'dumbbell',
      data: [
        { country: 'Rwanda', year: '2000', life: 48 },
        { country: 'Rwanda', year: '2020', life: 69 },
        { country: 'India', year: '2000', life: 63 },
        { country: 'India', year: '2020', life: 70 },
        { country: 'Brazil', year: '2000', life: 70 },
        { country: 'Brazil', year: '2020', life: 76 },
        { country: 'China', year: '2000', life: 72 },
        { country: 'China', year: '2020', life: 78 },
        { country: 'USA', year: '2000', life: 76 },
        { country: 'USA', year: '2020', life: 79 },
        { country: 'Japan', year: '2000', life: 81 },
        { country: 'Japan', year: '2020', life: 84 },
      ],
      encoding: { category: { field: 'country' }, value: { field: 'life', title: 'Years' }, group: { field: 'year' } },
      sort: 'gap',
      labels: true,
      format: ',.0f',
      title: 'Life expectancy gain, 2000 vs 2020',
    }),
  }),
  story({
    id: 'dumbbell-pay-gap',
    group: 'Dumbbell',
    title: 'Dumbbell — compensation bands',
    blurb: 'Dumbbells make benchmark gaps visible for every level while preserving exact endpoints.',
    tags: ['gap', 'people'],
    spec: () => ({
      type: 'dumbbell',
      data: [
        { level: 'L3', group: 'Current', pay: 108 },
        { level: 'L3', group: 'Market', pay: 116 },
        { level: 'L4', group: 'Current', pay: 136 },
        { level: 'L4', group: 'Market', pay: 151 },
        { level: 'L5', group: 'Current', pay: 176 },
        { level: 'L5', group: 'Market', pay: 190 },
        { level: 'L6', group: 'Current', pay: 221 },
        { level: 'L6', group: 'Market', pay: 236 },
        { level: 'L7', group: 'Current', pay: 285 },
        { level: 'L7', group: 'Market', pay: 292 },
      ],
      encoding: { category: { field: 'level' }, value: { field: 'pay', title: 'Total compensation ($k)', format: money }, group: { field: 'group' } },
      sort: 'ascending',
      labels: true,
      format: money,
      title: 'Compensation band vs market benchmark',
    }),
  }),

  story({
    id: 'sankey-energy',
    group: 'Sankey',
    title: 'Sankey — energy supply to demand',
    blurb: 'Sankey links are source, target, and value rows; nodes and widths are derived.',
    tags: ['flow', 'energy'],
    wide: true,
    height: 460,
    spec: () => ({
      type: 'sankey',
      data: sankeyFlows('energy'),
      encoding: { source: { field: 'source' }, target: { field: 'target' }, value: { field: 'value', title: 'TWh' } },
      nodePadding: 16,
      nodeValues: true,
      title: 'Energy supply → demand',
    }),
  }),
  story({
    id: 'sankey-budget',
    group: 'Sankey',
    title: 'Sankey — revenue to net income',
    blurb: 'Financial flows are easier to audit when every split keeps proportional width.',
    tags: ['flow', 'finance'],
    wide: true,
    height: 430,
    spec: () => ({
      type: 'sankey',
      data: sankeyFlows('budget'),
      encoding: { source: { field: 'source' }, target: { field: 'target' }, value: { field: 'value', title: 'USD (000s)' } },
      nodeWidth: 18,
      nodePadding: 18,
      title: 'Revenue flow to net income',
    }),
  }),

  story({
    id: 'choropleth-states-adoption',
    group: 'Choropleth',
    title: 'Choropleth — state adoption index',
    blurb: 'The GeoJSON `name` property joins to one metric row per state in a pre-projected Albers map.',
    tags: ['map', 'geo'],
    wide: true,
    height: 480,
    spec: () =>
      ({
        type: 'choropleth',
        geo: usStates,
        data: choroplethMetric(usStateNames, { seed: 51, base: 40 }),
        encoding: { key: { field: 'name' }, color: { field: 'value', title: 'Adoption index', type: 'quantitative' } },
        featureId: 'name',
        projection: 'identity',
        scheme: 'teal',
        title: { text: 'Adoption index by state', subtitle: 'Higher values indicate stronger product penetration' },
      }) as ChartSpec,
  }),
  story({
    id: 'choropleth-states-density',
    group: 'Choropleth',
    title: 'Choropleth — population density',
    blurb: 'The same map geometry can join feature-derived values for an alternate regional story.',
    tags: ['map', 'density'],
    wide: true,
    height: 480,
    spec: () =>
      ({
        type: 'choropleth',
        geo: usStates,
        data: usStates.features.map((f) => ({ name: f.properties?.name, density: f.properties?.density })),
        encoding: { key: { field: 'name' }, color: { field: 'density', title: 'People / sq mi', type: 'quantitative' } },
        featureId: 'name',
        projection: 'identity',
        scheme: 'teal',
        title: 'Population density by state',
      }) as ChartSpec,
  }),

  story({
    id: 'table-order-health',
    group: 'Table',
    title: 'Table — regional order health',
    blurb: 'Grouped columns, totals, data bars, icon sets, and risk rules make tables first-class specs.',
    tags: ['table', 'conditional-formatting'],
    wide: true,
    height: 520,
    spec: () => ({
      type: 'table',
      data: tableRows(),
      columns: [
        { field: 'order', title: 'Order', group: 'Order' },
        { field: 'account', title: 'Account', group: 'Order', wrap: true },
        { field: 'region', title: 'Region', group: 'Order' },
        { field: 'category', title: 'Category', group: 'Order' },
        { field: 'units', title: 'Units', align: 'right', group: 'Volume', total: 'sum' },
        { field: 'sales', title: 'Sales', format: ',.0f', prefix: '$', align: 'right', group: 'Financials', total: 'sum', conditionalFormat: { type: 'bar', showValue: true } },
        { field: 'profit', title: 'Profit', format: ',.0f', prefix: '$', align: 'right', group: 'Financials', total: 'sum', negativeStyle: 'parens-red', conditionalFormat: { type: 'bar', baseline: 'zero' } },
        { field: 'margin', title: 'Margin', format: '.1%', align: 'right', group: 'Financials', conditionalFormat: { type: 'colorScale', scheme: 'teal', diverging: true, midpoint: 0.25 } },
        { field: 'margin', title: 'Trend', format: '.1%', align: 'right', group: 'Signals', conditionalFormat: { type: 'icon', set: 'arrows', position: 'left' } },
        { field: 'risk', title: 'Risk', group: 'Signals' },
        { field: 'riskScore', title: 'Risk score', align: 'right', group: 'Signals', conditionalFormat: { type: 'rules', rules: [{ when: 'gte', value: 3, weight: 'bold', icon: '!' }, { when: 'between', value: 2, to: 2, icon: '•' }] } },
      ],
      density: 'compact',
      totals: { label: 'Portfolio' },
      sort: { field: 'sales', order: 'desc' },
      title: 'Regional order health',
    }),
  }),
  story({
    id: 'table-customer-ledger',
    group: 'Table',
    title: 'Table — customer ledger',
    blurb: 'A lighter ledger demonstrates sortable business records with readable financial formatting.',
    tags: ['ledger', 'orders'],
    wide: true,
    height: 440,
    spec: () => ({
      type: 'table',
      data: salesTable({ n: 12, seed: 39 }),
      columns: [
        { field: 'order', title: 'Order' },
        { field: 'date', title: 'Date', format: '%b %e, %Y' },
        { field: 'region', title: 'Region' },
        { field: 'segment', title: 'Segment' },
        { field: 'category', title: 'Category' },
        { field: 'units', title: 'Units', align: 'right' },
        { field: 'sales', title: 'Sales', format: money, align: 'right', conditionalFormat: { type: 'bar' } },
        { field: 'margin', title: 'Margin', format: '.1%', align: 'right', conditionalFormat: { type: 'colorScale', scheme: 'teal' } },
      ],
      density: 'standard',
      sort: { field: 'sales', order: 'desc' },
      title: 'Customer order ledger',
    }),
  }),

  story({
    id: 'matrix-revenue-pivot',
    group: 'Matrix',
    title: 'Matrix — revenue pivot',
    blurb: 'Tidy rows pivot into row and column groups with totals and conditional formatting at render time.',
    tags: ['pivot', 'matrix'],
    wide: true,
    height: 520,
    spec: () => ({
      type: 'matrix',
      data: salesTable({ n: 240, seed: 73 }),
      rows: ['region', 'segment'],
      columns: ['category'],
      values: [
        { field: 'sales', op: 'sum', label: 'Sales', format: money, conditionalFormat: { type: 'colorScale', scheme: 'teal' } },
        { field: 'sales', op: 'sum', label: '% total', showAs: 'percentOfTotal', conditionalFormat: { type: 'bar' } },
      ],
      subtotals: true,
      grandTotals: true,
      density: 'compact',
      columnSort: { by: 'value', valueIndex: 0, order: 'desc' },
      title: { text: 'Revenue mix by region', subtitle: 'Sales and percent of total by category' },
    }),
  }),
  story({
    id: 'matrix-margin-share',
    group: 'Matrix',
    title: 'Matrix — margin share of row',
    blurb: 'Show-as calculations convert leaf cells into row percentages without precomputed totals.',
    tags: ['show-as', 'percent-of-row'],
    wide: true,
    height: 500,
    spec: () => ({
      type: 'matrix',
      data: salesTable({ n: 240, seed: 73 }),
      rows: ['category'],
      columns: ['region', 'segment'],
      values: [
        { field: 'profit', op: 'sum', label: 'Profit', format: money, negativeStyle: 'parens-red', conditionalFormat: { type: 'colorScale', scheme: 'teal', diverging: true, midpoint: 0 } },
        { field: 'sales', op: 'sum', label: '% row sales', showAs: 'percentOfRow', conditionalFormat: { type: 'bar' } },
      ],
      grandTotals: true,
      density: 'compact',
      title: 'Profit and sales mix by category',
    }),
  }),
];
